### ISSUE TITLE
openstack pike with openvswitch

### ISSUE THREAD

**Issue by TrongTan124** [hocchudong/thuctap012017#136]
link hướng dẫn: https://github.com/hocchudong/thuctap012017/blob/master/XuanSon/OpenStack/Install_OPS/Pike/Install_OPS_with_OVS/Controller_Self-service_networks.md

tại sao cấu hình DHCP (/etc/neutron/dhcp_agent.ini) ko sử dụng DNSmasq. các VM lấy IP từ đâu?

**Comment by congto** [comment]
@TrongTan124 lần sau gửi issue thì  tag người cần trao đổi vào nhé, ví dụ @doxuanson

**Comment by doxuanson** [comment]
cái này em cũng không rõ ạ! Cấu hình dhcp agent khi cài "OpenStack với OpenvSwitch" người ta bỏ tùy chọn đó!
