### ISSUE TITLE
Chỉnh lại bước 2 trong tài liệu lab về PXE

### ISSUE THREAD

**Issue by congto** [hocchudong/thuctap012017#142]
@ThanhTamPotter 

Em kiểm tra lại tài liệu này, anh thấy bước 2 đang hiển thị xấu quá, 

https://github.com/hocchudong/thuctap012017/blob/master/TamNT/PXE-Kickstart/docs/2.Lab_PXE-kickstart.md

**Comment by ThanhTamPotter** [comment]
a @congto em edit lại hết rồi ạ!

**Comment by congto** [comment]
@ThanhTamPotter ok em
