### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by TrongTan124** [hocchudong/thuctap012017#159]
@doxuanson  kiểm tra lại script https://github.com/hocchudong/thuctap012017/blob/master/XuanSon/OpenStack/Install%20OpenStack/Pike/Install_OPS_with_OVS/scripts/ctl-4-nova.sh

Phần tạo user DB cho nova chưa thay biến password. dẫn tới đổi password trong config khác với Welcome123 sẽ false

Thêm file https://github.com/hocchudong/thuctap012017/blob/master/XuanSon/OpenStack/Install%20OpenStack/Pike/Install_OPS_with_OVS/scripts/com-2-nova.sh
ở dòng 47 nhé

NOTE:
Sau khi cài đặt xong compute, phải vào controller chạy lệnh: 
su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
==> sẽ tìm và cập nhật các node compute.
Hoặc phải thêm cấu hình vào file /etc/nova/nova.conf
==>
[scheduler]
discover_hosts_in_cells_interval = 300

**Comment by doxuanson** [comment]
@TrongTan124 
- Em đã fix lỗi rồi ạ!
- Phần discovery các host compute thì em đã viết scripts để chạy!

**Comment by congto** [comment]
@doxuanson cái này em đã pull request lại chưa?
